### ISSUE TITLE
Trees aren't collapsible?

### ISSUE THREAD

**Issue by sophiebits** [bvaughn/react-devtools-experimental#105]
Not sure if I'm missing something obvious, but I don't see any disclosure triangles or similar ways to expand and collapse parts of the tree. This means that I always see every component at every level. Is that expected?

**Comment by gaearon** [comment]
Yep. As far as I understand that’s the tradeoff to make virtualization of a tree feasible.

**Comment by bvaughn** [comment]
Yes. This version of DevTools is still a work in progress :grin:

https://github.com/bvaughn/react-devtools-experimental/blob/267ab34fbd713471fbf2da8e325c833e117c0a1f/src/devtools/views/Components/Element.js#L78

I still plan to _eventually_ implement toggle, but it will probably be tricky because of how I'm mapping the tree to a list and it doesn't seem a very high priority relative to all of the other stuff still needing to be done.

**Comment by gaearon** [comment]
I’m not sure how inherent it is though. Maybe there’s something smart we could do to enable this. In general I think that showing the whole tree makes it more difficult to think in terms of encapsulated components. Although the perf on large trees is too irresistible.

**Comment by bvaughn** [comment]
I'm not totally convinced that the collapse mechanism is still necessary for the new DevTools, since we have the owner list views that enable you to drill into a component, and the owner stack that lets you step back out. I was kind of waiting to hear if others (besides Sophie) mentioned missing this feature :)

**Comment by sophiebits** [comment]
> besides Sophie

Do I not count? :p I think it makes keyboard navigation mostly impractical (eg: can't switch between siblings by pressing Up/Down unless they're leaves), but maybe I'm an oddball.

**Comment by bvaughn** [comment]
I was also thinking/playing the other day with maybe using the right arrow key to skip over children tot he next sibling, as a way of fast stepping through the tree at a specific level. Not sure it felt "right" though, but maybe there's a keyboard shortcut option in there somewhere that would feel better?

> Do I not count?

You totally count! I should have said it a different way: "I was waiting if more than one or two people mention missing the feature". Believe it or not, so far you're the first!

**Comment by gaearon** [comment]
Fwiw I also often want to navigate siblings. Would be nice to figure out a solution for that even if we don’t do toggling.

**Comment by bvaughn** [comment]
Maybe up/down can continue to do previous/next...and left/right could siblings...left currently steps to parent but that's arguably not as important if you could just jump past the descendants of a previous sibling?

**Comment by sophiebits** [comment]
> it will probably be tricky because of how I'm mapping the tree to a list

Curious: What's the hard part here? My naive assumption was that when you collapse a node, you set its `.weight` to 1 and update ancestors correspondingly, then the other getElementAtIndex can remain the same. (Not sure if that would need to be a new `.visibleWeight` field or if it can replace the existing one.)

> and it doesn't seem a very high priority relative to all of the other stuff still needing to be done

Not sure what all you have in mind, but I tried this for the first time today and it looks/feels pretty complete to me at a first glance! This really is the biggest thing I've noticed so far.

**Comment by sophiebits** [comment]
(Looking forward to the release!)

**Comment by bvaughn** [comment]
> Curious: What's the hard part here?

It could be that it doesn't end up being that hard after all 😄 but I think there are tricky edge cases, like quickly detecting if you're in a collapsed tree when a tree-operation message comes in (so we don't incorrect increase/decrease the number of items in the "flat list"). I _think_ it's possible that this just works with very little code, but I'd need to spend some time testing it.

> Not sure what all you have in mind, but I tried this for the first time today and it looks/feels pretty complete to me at a first glance!

Thanks! 😁 We have a lot of ideas about tools for suspense, and I need to add support for React Native, etc. It is coming along nicely though!

**Comment by eps1lon** [comment]
> Not sure if I'm missing something obvious, but I don't see any disclosure triangles or similar ways to expand and collapse parts of the tree.

As far as I understand the new devtools is that you don't collapse/expand but fully step into a sub-tree<sup>1</sup>.

> This means that I always see every component at every level. Is that expected?

If you double click on a component you can *step into it* and you only see the sub-tree. 

![devtools-step](https://user-images.githubusercontent.com/12292047/55799676-3c21f080-5ad2-11e9-84c4-d634fdc41c4d.gif)


This solves most of my personal use cases.

There are still some UX issues with this though:
- general discoverability (maybe just always display the breadcrumbs)
- to go to the root I have to clear the breadcrumbs
- sub trees are only displayed shallow
- keyboard navigation in breadcrumbs?

I'm interested in working on these issues.

<sup>1</sup> Don't know the correct terminology. I saw "owner stack" somewhere else.

**Comment by bvaughn** [comment]
> to go to the root I have to clear the breadcrumbs

This is how you exit the mode. What's the UX concern? That it's not intuitive enough.

> sub trees are only displayed shallow

The "sub tree" is the tree of components the selected on "owns". This is the intentional design, but maybe it's not apparent from the UI?

> keyboard navigation in breadcrumbs?

Not sure I understand? Tab and enter should work for this. (Or arrow keys if it's in the collapsed "..." state.)

> can't search components in this view

I don't think this is a problem, per say, since these trees are almost always very small and visually scannable (at least in my experience).

**Comment by gaearon** [comment]
>The "sub tree" is the tree of components the selected on "owns". This is the intentional design, but maybe it's not apparent from the UI?

I was also confused by this. (But later figured this might be the case.) Is there any particular reason it should be this way? I haven't thought much about which behavior is better.

One thing to keep in mind is that in some cases we don't have owner information. Like with some HOCs or in production mode. In that case double-clicking produces a lonely node with no children, even though it has a large tree below.

**Comment by eps1lon** [comment]
> > to go to the root I have to clear the breadcrumbs
> 
> This is how you exit the mode. What's the UX concern? That it's not intuitive enough?

I don't want to exit the mode though. I want to view the top most owner. Maybe that's just an issue with the example because there isn't a single root but multiple siblings at the top? 

This is something I'm used to from the old devtools:
![devtools-breadcrumbs-old](https://user-images.githubusercontent.com/12292047/55825843-1236f100-5b07-11e9-8623-750b5db019c6.gif)
vs. new:
![devtools-breadcrumbs-new](https://user-images.githubusercontent.com/12292047/55825857-17943b80-5b07-11e9-9cb7-4f43a20f40b4.gif)

> keyboard navigation in breadcrumbs?

I described this poorly. What I meant was navigating the component tree with arrow keys and then being able to literally enter them (or left/right arrow keys like the old tools). But this only works in the owner view and only downwards. There is no way to go back up (backspace?). At the same time navigating through the tree with arrow keys should highlight the corresponding breadcrumb (old feature).

> This is the intentional design, but maybe it's not apparent from the UI?

Maybe add the closing slash to signal that a component has no children i.e. can't be stepped into. Currently I can still step into childless components which doesn't add much value IMO.

> > can't search components in this view
> 
> I don't think this is a problem, per say,

Having thought more about this I would agree.

**Comment by bvaughn** [comment]
> I don't want to exit the mode though. I want to view the top most owner. Maybe that's just an issue with the example because there isn't a single root but multiple siblings at the top?

You're already viewing the top-most owner in that stack. The example repo is a multi-root app (so I can test that the tree logic works with multiple roots).

> I described this poorly. What I meant was navigating the component tree with arrow keys and then being able to literally enter them (or left/right arrow keys like the old tools)

Hm. The old DevTools didn't let you "enter". There was no owner list view. I think left/right arrow keys work the same between both DevTools.

> At the same time navigating through the tree with arrow keys should highlight the corresponding breadcrumb (old feature).

I think this is a misunderstanding of the view. Arrow key navigation couldn't select a component up top, because the only component that would be both up top and in the tree is the currently selected one.

> Having thought more about this I would agree.

👍

**Comment by bvaughn** [comment]
> I was also confused by this. (But later figured this might be the case.) Is there any particular reason it should be this way? I haven't thought much about which behavior is better.

Because this seems like a useful way of exploring an app via DevTools. It's kind of like the DevTools equivalent to viewing the render functions.

> One thing to keep in mind is that in some cases we don't have owner information. Like with some HOCs or in production mode. In that case double-clicking produces a lonely node with no children, even though it has a large tree below.

For sure. We should disable the view if the owner field/info is missing!

**Comment by eps1lon** [comment]
> You're already viewing the top-most owner in that stack. The example repo is a multi-root app (so I can test that the tree logic works with multiple roots).

Gotcha. There's no issue here then.

> Hm. The old DevTools didn't let you "enter". There was no owner list view.

No but breadcrumbs and the concept of moving horizontally or vertically already existed. I don't thinks it far fetched to look at expanding a component tree in the old devtools being equivalent to selecting that component as the current owner in the new tools.

I guess allowing `left` at the current owner should go to the parent and `right` should be equivalent to `enter` in the owner view.

In the old devtools keyboard navigation was inspired by the visuals: up/down moved vertically in the view and left/right expanded/collapsed sideways. Maybe it makes more sense to use up/down for vertical movement in the tree (parent-child) and left/right horizontally (between siblings). Either way it should be consistent. 

> Because this seems like a useful way of exploring an app via DevTools. It's kind of like the DevTools equivalent to viewing the render functions.

Assuming the render functions only have own level of nesting though? I think shallow rendering describes this better.

**Comment by bvaughn** [comment]
It looks like this discussion is starting to spread out. I'd like to keep this issue focused on collapsable nodes. Separate things can be talked about on a separate issue.

**Comment by bvaughn** [comment]
> Curious: What's the hard part here?

Circling back around to Sophie's original question.

I had originally hoped that collapsing a node could be done quickly, by just updating its parent's "weight" by subtracting its own weight (less one - aka the sum of its immediate children's weight), but that might not be sufficient because of the way the built-in search functionality works.

The search reducer needs to know about when elements are added or removed from the tree in order to update its results and its currently selected item index To generate this list, toggling a node would _require_ us to traverse all of its descendants to generate the list of elements that were just "added" or "removed" (from the visible set of elements).

Then again, maybe we can defer when this is needed to the point when a new search is run? (or when a new search result index is selected?)

Presumably, React DevTools should do what Chrome does and auto-expand nodes containing search results (when the search text changes). I assume as well that if you click the up/down arrow to select the next result, and that result is within a collapsed tree, the tree should auto-expand.

So maybe... we can just defer doing any search-related changes until the time when the search criteria change, then it would just require us to walk up the tree from a specific node- which would be a faster operation than recursing.

**Comment by bvaughn** [comment]
Got sidetracked by a bug this unearthed in react-window (https://github.com/bvaughn/react-window/commit/0b5a3d3) buuuuut, progress~

![tree-toggle](https://user-images.githubusercontent.com/29597/55840172-6201c200-5adf-11e9-80d0-d7b4c5be624f.gif)

Still need to sort out the search behavior, but so far so good.

**Comment by gaearon** [comment]
😮😮😮

**Comment by gaearon** [comment]
I’m not crying

**Comment by sophiebits** [comment]
so beautiful

**Comment by bvaughn** [comment]
Closer still!

Adding/removing elements within collapsed sub trees
![add-and-removedKapture 2019-04-09 at 17 42 05](https://user-images.githubusercontent.com/29597/55843803-f293ce80-5aee-11e9-8ba5-74b74f6a9b0a.gif)

Search results inside of a collapsed sub tree
![search-exapnd](https://user-images.githubusercontent.com/29597/55843818-00495400-5aef-11e9-9669-f56815be88be.gif)

**Comment by bvaughn** [comment]
Almost done! One more small thing to do (later tonight probably) with left/right arrows and I think it might be good to go?

I pushed an update to the now.sh demo if you want to play with it.

#116

**Comment by bvaughn** [comment]
Eh, that wasn't so hard either.

![left-right](https://user-images.githubusercontent.com/29597/55845063-270a8900-5af5-11e9-9ca4-d041594a3b6d.gif)

Pleasantly surprised with how this came together. Hoping I'm not overlooking obvious flaws. :)

**Comment by lucasecdb** [comment]
the demo on now.sh isn't collapsing the nodes on the "owner list" view

**Comment by lucasecdb** [comment]
also, for some reason selecting the nodes under the `Contexts` component doesn't select the node you've clicked on

![select bug](https://user-images.githubusercontent.com/10223856/55848011-fc82f500-5b21-11e9-8215-373d0db2fc63.gif)
