### ISSUE TITLE
Tree view tears across updates

### ISSUE THREAD

**Issue by sophiebits** [bvaughn/react-devtools-experimental#132]
Minor issue, but IMO still a bug…

Repro:

1. Go to https://react-devtools-experimental.now.sh/ and click "unmount test app" and "mount test app" repeatedly

Expected: With each click, the devtools tree view updates exactly once.
Actual: In most cases, you can see the List component appear or disappear before the others do, causing two visual updates in quick succession.

Since they are rendered in the same tick (and there is exactly one paint to the screen for the components themselves), I expect the devtools to paint once too.

(Tried to capture a GIF but it's hard to grab since it's a fast flicker.)

**Comment by bvaughn** [comment]
This is due to the current `Bridge` batching behavior:
https://github.com/bvaughn/react-devtools-experimental/blob/40469a190e79ea13cb482620055c05e221f64c17/src/bridge.js#L33-L45

We add 100ms delay in between messages. (The old DevTools did this too.) So the first root's unmount is quick, but the next ones get delayed and batched.

If you disable the batching (aka turn the duration to 0) then everything updates in the same tick.

**Comment by sophiebits** [comment]
That makes sense. Maybe needs some setImmediate up in there? So that messages in a single tick are always grouped.
