### ISSUE TITLE
Bad performance with Destiny Item Manager site

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-devtools-experimental#195]
This morning I got a report of DevTools performing poorly on the [Destiny Item Manager](app.destinyitemmanager.com) app (https://github.com/facebook/react-devtools/issues/681#issuecomment-484933097)

I _think_ this may be due to props being unexpectedly large (which we send through the bridge and try to render in the right hand side, inspected element panel). Initial Chrome profiling shows us spending a lot of time in this panel.

I think this is made _worse_ because of how we auto-select on hover when using the inspect button, and select triggers us to fetch props- so if you really quickly hover over a lot of items, we ask for all of their props.

I think we may want to do two things:
1. Re-think our serialization / hydration stuff so we can better handle huge props
2. Don't send the inspect request on mouse-over for the inspect button mode, but wait until the user clicks and confirms

**Comment by bvaughn** [comment]
> To get the Redux devtools to work, we had to blacklist a couple big properties using their support for filtering.

@bhollis You made this comment on the related repo issue. Could you tell me a little more about this? I'm not really that familiar with Redux DevTools. How does its blacklisting work? What did your blacklisting criteria look like?

Poking around the Destiny Item Manager app and looking at props, I do see a lot of pretty large arrays-or-arrays-of-strings that I'm not sure I understand the use case for.

**Comment by bhollis** [comment]
Thanks for looking into this!

Redux Devtools has [some configuration](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsanitizer--statesanitizer) that can be applied by the site itself, including some that prevent the extension from attempting to serialize or display certain properties. In DIM, [we configure this](https://github.com/DestinyItemManager/DIM/blob/master/src/app/store/store.ts#L14) to ignore the giant state items representing the game object definition database (~60MB) and the large data structure that defines your inventory.

I'm not sure exactly what props you encountered, but in general, the data model for DIM involves combining the game definitions (again, super huge) and the API response (also huge) into the detail you see on the screen. There's a lot of room for optimization here (for example, lazily computing item details instead of figuring it out all up front) but it's trickier than you'd think, and this is a 5+ year old codebase.

By the way, I don't know if devtools extensions can load source maps, but we ship source maps to production, so that could potentially help with any obfuscated objects.

**Comment by bhollis** [comment]
Drilling down from the root, the first component I hit that has issues is `Stores` which has [a prop that's the array of characters+vault](https://github.com/DestinyItemManager/DIM/blob/master/src/app/inventory/Stores.tsx#L20) that contains basically all the information that's shown on the main screen. [Here's the definition of that structure](https://github.com/DestinyItemManager/DIM/blob/master/src/app/inventory/store-types.ts#L65). I'm not sure exactly, but that object may even be self-referential (I haven't tracked down how, but there's a lot of sharing-by-reference instead of sharing-by-id).

**Comment by bhollis** [comment]
I did some investigation and I don't think the objects have any self-references/cycles - just cases where the same objects are organized in different ways (for example, a lists of all items, and then a separate list of items by category that is references to the same item objects).

**Comment by bvaughn** [comment]
Note to self: Maybe consider an approach like 0aa7d2f for a partial solution to this problem. (It would not be sufficient to fix the problem.)

**Comment by bvaughn** [comment]
Thanks for the added context, @bhollis

**Comment by gaearon** [comment]
How to reproduce the problem? Do I need to log into the website? I don't have any of those accounts.

**Comment by bhollis** [comment]
Let me think about it - right now it isn’t very useful if you don’t have game data but I’ve been meaning to check in some example API responses for offline development anyway.

**Comment by bvaughn** [comment]
I guess, worst case, I could share my Xbox Live login with Dan 😅 but having a way to use test data would be useful.

**Comment by bvaughn** [comment]
Looks like we had another use case pop up in FB5 today with a hook that had a reference to `document.body` in it. We need a better way to handle "heavy" props like this.

Somewhat vaguely related to #322

**Comment by bvaughn** [comment]
Hey @bhollis! Any interest in testing out a DevTools build with a fix for this issue? I can send you one if so.

**Comment by bvaughn** [comment]
@bhollis Here is a build for you to test (if you're interested):
[ReactDevTools.zip](https://github.com/bvaughn/react-devtools-experimental/files/3299398/ReactDevTools.zip)

**Comment by bhollis** [comment]
Awesome! I’m away from my computer until the end of the month but I’ll check it out when I’m back!
