### ISSUE TITLE
Profiler data gets lost when the inspected tab gets reloaded

### ISSUE THREAD

**Issue by sebmarkbage** [bvaughn/react-devtools-experimental#235]
If I have the Profiler open and the page reloads, then all the profiler data gets lost.

This also happens if you navigate somewhere else.

I noticed this on a page that auto-reloaded at some time. I kept randomly losing my Profile.

It should stay persistent even if I navigate or reload. Just as if I loaded the Profile from disk on any other random page.

I also have a problem where "Save profile..." just noops so I can't save the profile. I don't know why and it's not showing me any error or feedback. This means I can't actually Profile this page.

**Comment by bvaughn** [comment]
> It should stay persistent even if I navigate or reload.

DevTools (both this version and legacy) unmount and remount the extension on page navigation as a way of quickly cleaning up any stale state. We could revisit this decision and clean up in a different way if you think this functionality is that important. I think it probably wouldn't be too hard to do given the architecture.

> I also have a problem where "Save profile..." just noops so I can't save the profile. I don't know why and it's not showing me any error or feedback.

I think this is actually a Chrome extension API bug that I mentioned to Simeon (@DotProto). It seems that if you try to use the  `chrome.downloads.download` API within an extension that  is "docked" to the main browser window, it just silently fails. Once you undock (even if you re-dock later) it works again.

> This means I can't actually Profile this page.

I don't  understand what you mean by this comment. Why would being unable to save data prevent you from being able to profile? Or are you saying that the arbitrary reloads cause you to lose data before you're done with it?

**Comment by sebmarkbage** [comment]
Ah. I forgot that this was a Chrome bug.

> Or are you saying that the arbitrary reloads cause you to lose data before you're done with it?

Yea. If I could save it, at least I wouldn't have to try to replicate it when I lose it. However, even in that case it would still be pretty bad since I'd lose my place etc.

**Comment by bvaughn** [comment]
Thanks for clarifying!

**Comment by sompylasar** [comment]
> It should stay persistent even if I navigate or reload. Just as if I loaded the Profile from disk on any other random page.

Chrome DevTools Profiler has a notion of a profile session for that matter, and you have a menu to select one of those. Maybe we could add something like that to persist the profiling data (which is after page reload is actually irrelevant to the page itself). "Start profiling" and "Load from file" each would create new sessions in the menu.

By the way, does the profiling data fully describe what gets saved into a file, or does it talk to the live page to get some more info like the Components tab does?

**Comment by bvaughn** [comment]
I'm slightly resistant to this idea since it increases complexity and no one (up until now) has asked for it. I think export/import is sufficient for now.

> By the way, does the profiling data fully describe what gets saved into a file, or does it talk to the live page to get some more info like the Components tab does?

I'm not sure I understand what you're asking.

**Comment by sompylasar** [comment]
> > By the way, does the profiling data fully describe what gets saved into a file, or does it talk to the live page to get some more info like the Components tab does?
> 
> I'm not sure I understand what you're asking.

When fresh profiling is done (not loaded) and you're looking at the graphs/charts/etc, does it talk to the page to find out something additional, or is it all powered by a snapshot that contains all the info i.e. the same data you'd get if exported/imported?

I'm asking because if it is, persisting that is simple (you just "export" it to localStorage) and it's just a matter of changing one snapshot to an array of snapshots and adding a dropdown.

**Comment by bvaughn** [comment]
It comes entirely from the snapshot. It is meant to be shared with others who may not even have access to t he same application.

I remain slightly resistant to this idea for the same reasons as previously mentioned. When you focus  on a single feature, many things can be done relatively easy. But it's important to consider how they add up over time.

**Comment by sompylasar** [comment]
> I remain slightly resistant to this idea for the same reasons as previously mentioned. When you focus on a single feature, many things can be done relatively easy. But it's important to consider how they add up over time.

Yes, I appreciate your concern of testability and maintainability by a single person.

**Comment by sebmarkbage** [comment]
I’m not sure profiling sessions with multiple profiles at once is all that important since you could save each one and switch between them that way.

Throwing away the profile on reload is pretty annoying when this happens though because it doesn’t let me save it to begin with. It’s throwing away unsaved state. At least it would be nice if it would pop up a dialog that lets me save the profile before throwing it away. Then I could navigate to about: blank and open the profile there. It’s a little hacky but at least it’s possible to use the Profiler on a page like this. At the current state it’s not just annoying but not possible to use (without finding the source of the reloads and disabling them).

Depending on the set up this happens pretty often. Eg due to errors or hot reloading.

**Comment by sompylasar** [comment]
> At least it would be nice if it would pop up a dialog that lets me save the profile before throwing it away. Then I could navigate to about: blank and open the profile there.

I can try to prototype something like this if y'all are open to such behavior.

But I'm concerned with the other case where you want to reload and throw away but you're blocked on a disruptive modal dialog.

**Comment by sompylasar** [comment]
While investigating how profile sessions are exported currently, I found out that the related data types and structures would benefit from a cleanup first as they were quite spread out and a little misaligned, let alone Flow wasn't helping due to numerous `any` conversions, so here's the first step: https://github.com/bvaughn/react-devtools-experimental/pull/248

**Comment by bvaughn** [comment]
> I’m not sure profiling sessions with multiple profiles at once is all that important since you could save each one and switch between them that way.

Agreed.

> At least it would be nice if it would pop up a dialog that lets me save the profile before throwing it away. Then I could navigate to about: blank and open the profile there.

I don't know if it's possible for an extension to interrupt navigation, but I don't think it's a good user experience.

**Comment by bvaughn** [comment]
I woke up thinking about this for some reason. Jotted a few notes into my phone and wanted to leave them here for later.

* We recently changed DevTools to remove profiling data for a root any time that root was unmounted (to avoid unnecessary memory usage). This change would require us to undo that.
* In the Profiler tab, we could show drop-down menu- like Chrome for multiple profiling sessions, except ours would be a filtered list of every root with at least one commit during the most recent profiling session.
* This dropdown would have to display _something_ for each root. Maybe we could use a similar approach as the [renderer interface's "psuedo root key"](https://github.com/bvaughn/react-devtools-experimental/blob/17516b76ae763ec7c4dfa09d826164d6bb2e41c0/src/backend/renderer.js#L2258-L2290) where we displayed the first named component inside that root, and then a number beside it (if there's more than one). We would need to capture this data _early_ (and export it too) since the root might not exist when we're later viewing the profiling info.
* This would have the added benefit of letting you view profiling data even if a root was unmounted before Profiling completed. (Currently you select a root in the Components tree to view its profiling data.)
* We would need to avoid unloading DevTools between navigations. I think this should be safer to do now though, given that we've spent some time writing tests to ensure that we don't "leak" things. I think fear of potential leaking between was one of the big reasons DevTools originally remounted.

**Comment by bvaughn** [comment]
Sat down to take a look at this today and realized that I overlooked something initially that makes this a bit more complicated: Profiler data primarily lives in the injected renderer interface and is lazily requested via suspense. When the user navigates to a new page, the renderer interfaces is lost (since it lives in the page context). So even if we don't destroy the `Store`, it only ha sa partial copy of the data.

**Comment by sompylasar** [comment]
> Profiler data primarily lives in the injected renderer interface and is lazily requested via suspense. When the user navigates to a new page, the renderer interfaces is lost (since sit lives in the page context). 

Right, that's the thought I had when asked this

> By the way, does the profiling data fully describe what gets saved into a file, or does it talk to the live page to get some more info like the Components tab does?
>
> When fresh profiling is done (not loaded) and you're looking at the graphs/charts/etc, does it talk to the page to find out something additional, or is it all powered by a snapshot that contains all the info i.e. the same data you'd get if exported/imported?

**Comment by bvaughn** [comment]
I see. I thought the context of that thread was mostly regarding the ability to load/view multiple profiles at once, rather than the idea of persisting between pages.

**Comment by bvaughn** [comment]
I think the `devtools.network.onNavigated` API isn't enough to let us build this. It gets called _after_ the new page has loaded 😦 which makes sense, since an extension might react to this event by inject JavaScript into the page.

**Comment by bvaughn** [comment]
I guess we could take a step back and re-think the Profiler architecture a bit. Rather than using Suspense to fetch the data in small slices, we could send it all over the bridge eagerly when the user stops profiling (and maybe show a loading/processing bar). I guess Chrome does a similar thing after profiling when it's processing the data.

**Comment by sompylasar** [comment]
> I see. I thought the context of that thread was mostly regarding the ability to load/view multiple profiles at once, rather than the idea of persisting between pages.

That, too. I think it's all related and can rely on the same infra. Both page reload, page navigation, and load/view multiple relies on the ability to save/restore the whole thing at once.

**Comment by sompylasar** [comment]
> it could feel a bit annoying to have it sit and spin for a second after you stopped.

I think it's fine, that's what you'd expect from the built-in profiler. And that's likely not too long as react devtools collect less data, it seems.

**Comment by bvaughn** [comment]
Maybe we could use [`chrome.webNavigation.onBeforeNavigate`](https://developer.chrome.com/extensions/webNavigation#event-onBeforeNavigate) for this.

**Comment by bvaughn** [comment]
> That, too. I think it's all related and can rely on the same infra. Both page reload, page navigation, and load/view multiple relies on the ability to save/restore the whole thing at once.

Sure, it's all related- but they aren't all features that I think we should add to Profiler 😁

**Comment by sompylasar** [comment]
> Still not sure if we'd be able to block long enough for this to work.

You could try to use some sync XHR hack I guess. There's a way to substitute the navigation URL but I haven't found a way to block it.

**Comment by bvaughn** [comment]
I think I'm going to try refactoring the architecture to make this easier to support (#276).

**Comment by bvaughn** [comment]
I think the latest release (published just this morning) should now support this. We still unload the shell on navigate because it seems like the safest way to avoid potentially stale ports and listeners, _but_ before we do- we copy the current profiling data and pass it to the new instance so it remains accessible.

Let me know if anything seems funky and we can iterate.
