### ISSUE TITLE
Failed to read the 'localStorage' property from 'Window'

### ISSUE THREAD

**Issue by robertcoopercode** [bvaughn/react-devtools-experimental#292]
When installing the extension, I get an error for the Chrome extension that says the following:

```
Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

This error is preventing the React tabs from showing up in the Chrome Devtools for me.

![image](https://user-images.githubusercontent.com/16786990/58494024-2fb92c00-8142-11e9-8199-a3af67f8f595.png)

![image](https://user-images.githubusercontent.com/16786990/58493896-f1bc0800-8141-11e9-9ce8-f2197821b67d.png)

**Chrome Version 74.0.3729.169**

Feel free to close if you have no idea.

**Comment by bvaughn** [comment]
Sorry. This is the first I've seen or heard of this. 😦

**Comment by bvaughn** [comment]
Do you have "Block third-party cookies and site data" checked in Chrome's "Content Settings" ?

https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

**Comment by bvaughn** [comment]
Related https://github.com/apollographql/apollo-client-devtools/pull/185/files

**Comment by robertcoopercode** [comment]
> Do you have "Block third-party cookies and site data" checked in Chrome's "Content Settings" ?

Yes. I unchecked it and now the extension loads correctly! Thanks a lot 💯

**Comment by bvaughn** [comment]
Good to know. Thanks for the report. I'll try to see it degrades more gracefully in this case.

**Comment by bvaughn** [comment]
After thinking about this more, I believe it's a Chrome bug. Disabling cookies for a _website_ shouldn't disable the `localStorage` API for an extension, given that those two contexts are separate.

Unfortunately it looks like this has been reported to Chrome before, without any action being taken:
* https://bugs.chromium.org/p/chromium/issues/detail?id=319328
* https://bugs.chromium.org/p/chromium/issues/detailid=347140

I think working around it by using (the asynchronous) `chrome.storage` API is pretty tricky, because of timing issues during initialization. _At best_ we would have to completely drop support for the "reload and profile" feature. It would also make user settings in more complicated in general, particularly component filters.

**Comment by bvaughn** [comment]
For now I have at least fixed the runtime error by wrapping all calls to `localStorage`/`sessionStorage` in `try`/`catch` so the extension doesn't fail. (71bfb34)

Should be able to install the latest to get this fix. Going to close this issue in our repo for now, since I don't plan to act on it further (at least not yet, pending more info on the crbug).

**Comment by itssaifurrehman** [comment]
![solution](https://user-images.githubusercontent.com/50805617/74569652-e5364480-4f48-11ea-8dc9-4b23bd8ea1a8.png)
Hope this works for you. It worked for me

**Comment by BenCoughlan15** [comment]
Hi, trying to do this on the browserless chrome image.
https://hub.docker.com/r/browserless/chrome/

Any idea how I unset the "block third party cookies and site data" setting in cli mode? 

cheers,
Ben

**Comment by bvaughn** [comment]
Nope, sorry. You'll have to search the Chrome docs.
