### ISSUE TITLE
Discussion: Component bookmarks

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-devtools-experimental#305]
Product developers sometimes find it useful to jump back and forth between a few components in a tree. Currently this requires scrolling or using the selection tool. Maybe we could allow you to temporarily bookmark one or more components somehow? Then the existing Search interface could maybe be repurposed to let you step between bookmarked components (when there's no search text).

These bookmarks would probably not need to be persisted between reloads, so they could be associated with the specific in-memory element<sup>1</sup>.

<sup>1</sup> Although this association would be lost with a filter change.

**Comment by JoseRenan** [comment]
Hey, @bvaughn, this would be a really nice feature. I was thinking about putting a bookmarks bar below the search bar (if there are bookmarks) like this:
![image](https://user-images.githubusercontent.com/11728746/62434106-aad42b00-b70d-11e9-96fc-feebb0bbef1a.png)
Another thing I was wondering is if isn't it better to bookmark search filter instead of components itself :thinking:

**Comment by fanny** [comment]
I agree with you @JoseRenan, imo using search filter, it decrements the implementation complexity, if the user needs select the component manually, it would be necessary add other option in a menu, when component is selected and after that, save in some structure. Reusing filter becomes more simple, to retrieve and save element.

**Comment by bvaughn** [comment]
This repository is being merged into the main React repo ([github.com/facebook/react](https://github.com/facebook/react/)). As part of this, I am moving all issues to that repository as well and closing them here.

This issue has been relocated to:
https://github.com/facebook/react/issues/16478
