### ISSUE TITLE
Architecture Questions

### ISSUE THREAD

**Issue by marvinhagemeister** [bvaughn/react-devtools-experimental#31]
The new devtools look really amazing and are a huge level-up! The interface is much nicer and feels smoother to me 👍 I'm currently working my way through the `Overview` document and have a few questions:

**1. What counts as an owner?**

We don't have something like that in Preact, but I guess this is a pointer to the parent `vnode/fiber`?

**2. What's the shape of an `inspectElement` message?**

The document has a section about requesting additional information (`props`, `states`, maybe `hooks`?) via a a dedicated `inspectElement` message. The definition for it is not present in the paper. Maybe it's currently in progress (the repo has "experimental" in the title after all :) )

**3. Strict message order like in the current devtools?**

The current devtools expect the events to be sent in a very specific order. The document mentions that the goal is to only sent patches across the barrier. If I understand it correctly it means that the strict order isn't necessary anymore, but could be encouraged for performance reasons depending on how the extension works. When we're just sending patches, can effectively skip generating an event for a `fiber` that hasn't changed at all?

**4. Is there any rough ETA?**

I'm mainly asking because at some point we'll need to switch to the new protocol for preact. Do we need to start working on it right now or is the release a few weeks/months off in the future?

All in all I love the direction the devtools are taking! That's some really cool stuff you're working on 👍 Moving the instance detection to the adapter instead of doing it inside the extension is a great move and will make our integration a lot easier. Really looking forward to this 💯

**Comment by bvaughn** [comment]
Thanks for the kind words!

I don't have a lot of bandwidth for questions in this repo at the moment, so my answers are going to be brief.

> **1. What counts as an owner?**
We don't have something like that in Preact, but I guess this is a pointer to the parent `vnode/fiber`?

The owner is the component that created the React element.

```js
function Foo() {
  return <Bar><Baz /></Bar>;
}
```

Even though `Bar` is the _parent_ of `Baz`, `Foo` is the _owner_ of both `Bar` and `Baz`.

> **2. What's the shape of an `inspectElement` message?**
The document has a section about requesting additional information (`props`, `states`, maybe `hooks`?) via a a dedicated `inspectElement` message. The definition for it is not present in the paper. Maybe it's currently in progress (the repo has "experimental" in the title after all :) )

The overview isn't meant to be exhaustive. Curios folks will still have to look at the code itself. I mostly wrote this as a way of sharing my ideas/approach with the React core team (and others who are interested).

Inspect message is sent from the front-end here:
https://github.com/bvaughn/react-devtools-experimental/blob/2d6800728889a5141b7a1c08842f2e90ffc9448a/src/devtools/views/Elements/SelectedElement.js#L246

Response is sent here:
https://github.com/bvaughn/react-devtools-experimental/blob/2d6800728889a5141b7a1c08842f2e90ffc9448a/src/backend/agent.js#L122

Actual response is built here:
https://github.com/bvaughn/react-devtools-experimental/blob/2d6800728889a5141b7a1c08842f2e90ffc9448a/src/backend/renderer.js#L1139

> **3. Strict message order like in the current devtools?**
The current devtools expect the events to be sent in a very specific order. The document mentions that the goal is to only sent patches across the barrier. If I understand it correctly it means that the strict order isn't necessary anymore, but could be encouraged for performance reasons depending on how the extension works. When we're just sending patches, can effectively skip generating an event for a `fiber` that hasn't changed at all?

Tree patches still require ordering, else we might end up trying to add a child to a node that has been removed. Fortunately _most_ changes don't require any update since they don't affect the structure of the tree. This is another case where you'll probably want to dig into the source to see the details, e.g. here:
https://github.com/bvaughn/react-devtools-experimental/blob/e5280307c920279c6607c612fe066847505b1ee3/src/backend/renderer.js#L687-L690

> **4. Is there any rough ETA?**
I'm mainly asking because at some point we'll need to switch to the new protocol for preact. Do we need to start working on it right now or is the release a few weeks/months off in the future?

Not at the moment. I'll share an ETA pretty openly when I have one.

Probably goes without saying but I'm not going to offer any kind of _official_ support for Preact with the new DevTools (or even React <16) but I guess that's always been the case and you folks have been able to make it work so 👍

**Comment by marvinhagemeister** [comment]
Currently playing around with our integration and just want to amend that it's so much better that clients/renderers can do all the instance mapping to `id`s themselves :+1: :+1: It makes writing tests a breeze because now you have a serializable json structure for events that can be easily verified :100:

**Comment by bvaughn** [comment]
Well that's nice to hear
