### ISSUE TITLE
React Devtools Extension tabs don't show up when Video Downloader Plus extension is enabled

### ISSUE THREAD

**Issue by mohsinulhaq** [bvaughn/react-devtools-experimental#311]
https://chrome.google.com/webstore/detail/video-downloader-plus/fhplmmllnpjjlncfjpbbpjadoeijkogc

React Devtools Experimental tabs don't show up when the above extension is enabled. Logging this as a heads up for potential clashes with other extensions as well.

**Comment by bvaughn** [comment]
Thanks for the heads up. That extension appears to be writing  to `__REACT_DEVTOOLS_GLOBAL_HOOK__` which definitely interferes with this extension. I'm not sure what I can do about that really, since that extension isn't controlled by anyone Facebook related.

Going to close this issue since I can't do much about it, but I appreciate you letting me know.

**Comment by mohsinulhaq** [comment]
Just FYI, original devtools works fine with this extension enabled. I see this issue only when using the new one.

**Comment by bvaughn** [comment]
Original DevTools implementation is significantly different than the new one, in order to support e.g. reload-and-profile and sharing state (e.g. profiling info) across page navigations. Assuming what you say is true, even if I updated this extension to behave more like the old one, it would still be a race case essentially as to which extension got loaded first. (That extension might still clobber the DevTools extension if it was initialized afterward and override the global hook.)

**Comment by mohsinulhaq** [comment]
Oh ok, seems reasonable. Thanks for the clarification!
