### ISSUE TITLE
Hook label is sometimes empty

### ISSUE THREAD

**Issue by gaearon** [bvaughn/react-devtools-experimental#328]
<img width="142" alt="Screen Shot 2019-06-18 at 5 40 21 PM" src="https://user-images.githubusercontent.com/810438/59703353-95ed1800-91f1-11e9-8db9-6980d020935f.png">

Seeing this in `FB5TopNavBar`.

**Comment by bvaughn** [comment]
It looks like the source code in this  example has a "custom hook" that's assigned to a variable (e.g. `useFoo`) but is being created by a helper function (which returns an anonymous function, so there's no actual name being associated with the hook). So that's the first problem.

A second related problem is that FB's lazy/inline requires are resulting in this function being named e.g. "__annotator.module" in DEV (and empty string in prod).

**Comment by bvaughn** [comment]
![Screen Shot 2019-06-18 at 11 36 46 AM](https://user-images.githubusercontent.com/29597/59710252-7b00b080-91bd-11e9-895f-0497877937a2.png)

DevTools will, for now, just  display these as dimmed "Anonymous"

Fixed in abc8ef3, deploying now.
