### ISSUE TITLE
[Firefox] NS_ERROR_FILE_CORRUPTED

### ISSUE THREAD

**Issue by visualcookie** [bvaughn/react-devtools-experimental#34]
Hey,

while trying to add it as temporary add-on it results in an error, no matter how I do it. Current React Devtools is disabled.

Firefox Version: Developer Edition 67.0b4 (64-bit)

Full error message:
```
There was an error during installation: Error while loading 'jar:file:///Users/deanhidri/Downloads/packed.zip!/manifest.json' (NS_ERROR_FILE_CORRUPTED)
```

**Comment by bvaughn** [comment]
Hi @visualcookie. Sorry to hear that the extension isn't installing correctly for you.

For what it's worth, the Firefox extension (and installation) works for me with both Firefox versions 65.0.1 and 66.0.1 as well as Firefox Developer Edition 67.0b4.

I'm not sure why you're seeing the error you mention. Seems like it might have something to do with the browser's local (or session) storage being corrupted. Unfortunately, you'll have to sort this one out because I don't really have the bandwidth to provide support on this repo. As the name and the project readme specify, it's still in the experimental stage. 😅

I'd appreciate if you'd leave a comment here when you figure out the cause though (in case it helps others). Good luck!
