### ISSUE TITLE
Props editor hard to enter negative number

### ISSUE THREAD

**Issue by samdenty** [bvaughn/react-devtools-experimental#346]
If you select all on a number prop and try to type in a negative value, it won't allow you.

You have to type the number in first, then add a negative sign.

**Comment by bvaughn** [comment]
Hm... that's because we are currently parsing the value to ensure it stays a number:
https://github.com/bvaughn/react-devtools-experimental/blob/39a811debee5a520d3a6034b429e8877e11331aa/src/devtools/views/Components/EditableValue.js#L36-L37

I suppose we could delay that conversion (string -> number) until/unless the changed value was actually applied:
https://github.com/bvaughn/react-devtools-experimental/blob/39a811debee5a520d3a6034b429e8877e11331aa/src/devtools/views/Components/EditableValue.js#L62-L63
