### ISSUE TITLE
The Context hook is not shown unless another hook is also presen like useState or useEffect

### ISSUE THREAD

**Issue by vnvizitiu** [bvaughn/react-devtools-experimental#378]
When I have a component that only uses a **useContext**, the hooks section is not show, but if I register a hook for state or effect, then I can inspect the context hook.

Using version **a6aba5a** but I noticed this for a while and I saw that there was no issue submitted at this (at least from a title point of view)

**Comment by bvaughn** [comment]
[DevTools needs to re-render function components to display hooks values.](https://github.com/bvaughn/react-devtools-experimental/blob/master/OVERVIEW.md#inspecting-hooks) In order to avoid tripping breakpoints, logging, etc. unnecessarily- it only does this when it can tell the component uses hooks. Unfortunately `useContext` isn't detectable on its own, because it doesn't write anything to the internal state field. (It's just a small wrapper around the context API.)

So the options here are either:
1. Do nothing, and functions that only use `useContext` will continue to be skipped.
2. Always re-render every function component, even if it's unlikely to use hooks, in case it uses _only_ `useContext`.

Neither option seems great or like the obvious right choice.

**Comment by vnvizitiu** [comment]
I'm fine with having it be skipped cause for debugging purposes I could run an empty effect or a bogus state.

Did not know what's involved in having that happen.

At least this is logged for future reference. The issue can be closed or kept some possible future innovation 😃

**Comment by bvaughn** [comment]
No worries. It's an interesting issue for sure.

**Comment by sebmarkbage** [comment]
@bvaughn useContext writes to the dependencies field so it’s detectable there.

**Comment by bvaughn** [comment]
Ah!

DevTools currently "detects" the use of hooks by looking for a non-null `memoizedState` field. We could expand that check to also include non-null `dependencies` field as well.

Nice suggestion :smile: Thanks

**Comment by bvaughn** [comment]
Fixed in f616613. Will be released later today in v4.0.3

**Comment by bvaughn** [comment]
v4.0.3 has just been released with this fix.

Full changelog: https://github.com/facebook/react/blob/master/packages/react-devtools/CHANGELOG.md#403-august-17-2019
