### ISSUE TITLE
prerelease editable props "tab press" not working

### ISSUE THREAD

**Issue by mdugue** [bvaughn/react-devtools-experimental#50]
Really looking forward to **React DevTools 4.0.0** turning stable!

Here's a little glitch I realised whilst using it, couldn't find any related issue yet:

1. Select an element in React DevTools
2. Edit it's props / state and press `Tab` – change won't be applied
_(note: if you press `Enter` – changes will be applied)_

While not necessarily a bug, I found it confusing as pressing tab is what I usually do in chrome dev tools.

**Comment by bvaughn** [comment]
Thanks for the feedback.

I wouldn't call this a "glitch". It was an intentional choice to require "enter" to confirm the edits.

I understand and appreciate that the difference between this and  e.g. Chrome's style editor may cause confusion, so I'll keep this feedback in mind if I hear similar concerns from others. For now though- I'm going to leave the behavior as-is.

(I'm not really focused on that level of polish yet in the rewrite, still adding broad features.)

**Comment by sophiebits** [comment]
I came to this repo to report this exact bug. If Tab doesn't commit, I would suggest the field revert back to the old value when it loses focus. That said, I think committing on Tab is a better behavior.
